In [1]:
import pandas as pd
import glob
import os
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression, LinearRegression

In [8]:
#Reading the general world news headlines 

# path =r'kiran' # use your path
# allFiles = glob.glob(path + "/*.csv")
# data = pd.DataFrame()
# list_ = []
# for file_ in allFiles:
#     df = pd.read_csv(file_,index_col=None, header=0)
#     list_.append(df)
# data = pd.concat(list_)
# data = data.sort_values(['Date','Direction', 'Headline'], ascending=[True,False,True])
# data.head()

In [4]:
data = pd.read_csv('headlines_csv/combine.csv')
data.head()

,Date,Direction,Headline,Headline.1,Headline.2,Headline.3,Headline.4,Headline.5,Headline.6,Headline.7,...,Headline.77,Headline.78,Headline.79,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88
0,1/1/2006,0.0,"With Charges Aired, Coach Is Suspended And In...",Bankruptcy? Tougher Than Counseling a Soprano,"At New York's Mayoral Inaugurations, Ask Not ...",Antidepressants Seem to Cut Suicide Risk in T...,Can You Revive an Extinct Animal?,"Paid Notice: Memorials BIGGART, EMILY B.",Maybe the Stock Pickers Have Gone Fishing,Something to Say About the Movie? By All Mean...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1/2/2006,0.0,STATES TAKE LEAD IN PUSH TO RAISE MINIMUM WAGES,BUSINESS DIGEST,"Holiday Is Over, but the Business Goes On; In...",Sports of The Times; Barber as the M.V.P. Wou...,'Casanova' Illuminated By Masters Of Baroque,Sunni Rights and Wrongs in Iraq,Advertising's Twilight Zone: That Signpost Up...,Pakistanis Back Off Vow To Control Seminaries,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1/3/2006,1.0,The Risks of Screenings,"Well Served As Patients, Dissatisfied As Cust...",4 Arrested in Theft of Baby Jesus Figurines,The Depression-Holiday Link,Risks Ahead As Policies (And Money) Tighten i...,Union Dissidents Say Transit Leader Gave Away...,"How's Business? Picking Up, With a Smile",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1/4/2006,1.0,BUSINESS DIGEST,Woman in the News: Christine Callaghan Quinn;...,"Paid Notice: Deaths WEISS, BLANCHE",Caught Up in a Turf War On Winnipeg's Mean St...,"Awaiting Word From Below, Relatives Honor the...","Apartment Sales Decline, But Manhattan Prices...","Paid Notice: Deaths MCCARTHY, LAWRENCE F.",National Briefing | New England: Massachusett...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1/5/2006,1.0,Apple of Someone Else's Eye,Smile Like You Mean It,The Hazards and Rewards Of Opening With a Low...,BUSINESS DIGEST,"Paid Notice: Deaths RUBIN, EMILY",Inquiry in 1992 Mob Killing Focuses on Ex-F.B...,Russia and Ukraine Reach Compromise on Natura...,"Paid Notice: Deaths MCCARTHY, LAWRENCE F.",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# data['Date']
train = pd.read_csv('headlines_csv/train.csv')
test = pd.read_csv('headlines_csv/test.csv')
train.head()

,Date,Direction,Headline,Headline.1,Headline.2,Headline.3,Headline.4,Headline.5,Headline.6,Headline.7,...,Headline.77,Headline.78,Headline.79,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88
0,1/1/2006,0,"With Charges Aired, Coach Is Suspended And In...",Bankruptcy? Tougher Than Counseling a Soprano,"At New York's Mayoral Inaugurations, Ask Not ...",Antidepressants Seem to Cut Suicide Risk in T...,Can You Revive an Extinct Animal?,"Paid Notice: Memorials BIGGART, EMILY B.",Maybe the Stock Pickers Have Gone Fishing,Something to Say About the Movie? By All Mean...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1/2/2006,0,STATES TAKE LEAD IN PUSH TO RAISE MINIMUM WAGES,BUSINESS DIGEST,"Holiday Is Over, but the Business Goes On; In...",Sports of The Times; Barber as the M.V.P. Wou...,'Casanova' Illuminated By Masters Of Baroque,Sunni Rights and Wrongs in Iraq,Advertising's Twilight Zone: That Signpost Up...,Pakistanis Back Off Vow To Control Seminaries,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1/3/2006,1,The Risks of Screenings,"Well Served As Patients, Dissatisfied As Cust...",4 Arrested in Theft of Baby Jesus Figurines,The Depression-Holiday Link,Risks Ahead As Policies (And Money) Tighten i...,Union Dissidents Say Transit Leader Gave Away...,"How's Business? Picking Up, With a Smile",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1/4/2006,1,BUSINESS DIGEST,Woman in the News: Christine Callaghan Quinn;...,"Paid Notice: Deaths WEISS, BLANCHE",Caught Up in a Turf War On Winnipeg's Mean St...,"Awaiting Word From Below, Relatives Honor the...","Apartment Sales Decline, But Manhattan Prices...","Paid Notice: Deaths MCCARTHY, LAWRENCE F.",National Briefing | New England: Massachusett...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1/5/2006,1,Apple of Someone Else's Eye,Smile Like You Mean It,The Hazards and Rewards Of Opening With a Low...,BUSINESS DIGEST,"Paid Notice: Deaths RUBIN, EMILY",Inquiry in 1992 Mob Killing Focuses on Ex-F.B...,Russia and Ukraine Reach Compromise on Natura...,"Paid Notice: Deaths MCCARTHY, LAWRENCE F.",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
example = train.iloc[2,2]
example2 = example.lower()

In [12]:
example3 = CountVectorizer().build_tokenizer()(example2)
print(example3)

['the', 'risks', 'of', 'screenings']

In [13]:
pd.DataFrame([[x,example3.count(x)] for x in set(example3)], columns = ['Word', 'Count'])

         Word  Count
0          of      1
1         the      1
2       risks      1
3  screenings      1

In [6]:
#Get the headlines

trainheadlines = []
for row in range(0,len(train.index)):
    trainheadlines.append(' '.join(str(x) for x in train.iloc[row,2:82]))
    
trainheadlines[0]

" With Charges Aired, Coach Is Suspended And Inquiry Opens  Bankruptcy? Tougher Than Counseling a Soprano  At New York's Mayoral Inaugurations, Ask Not for a Great Speech  Antidepressants Seem to Cut Suicide Risk in Teenagers and Adults, Study Says  Can You Revive an Extinct Animal?  Paid Notice: Memorials   BIGGART, EMILY B.  Maybe the Stock Pickers Have Gone Fishing  Something to Say About the Movie? By All Means, Speak Up  Making a Push On Pocketbook Issues  Paid Notice: Deaths   ZABRISKIE, PHILIP TYLER, B.  New Yorkers Who Earn The Minimum Get a Raise  Districts Know the Value Of Real Estate Agents  Putin Offers 3-Month Extension of Ukraine's Gas Subsidy  Ready for Everything Under the Solar Panel  Pension Issue Persists After the Transit Strike  More Open Space, More Affordable Housing  Pension Issue Persists After the Transit Strike  OFFICIALS AT U.N. SEEK FAST ACTION ON RIGHTS PANEL  In New Jersey, Party Bosses Meld Politics And Business  STREETSCAPES/The Beaux-Arts Ball; A New Age Of Architecture Ushered In Financial Gloom  Paradise Found, Limbo Lost nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan"

In [7]:
# Tokenizing

basicvectorizer = CountVectorizer(ngram_range=(2,2))
basictrain = basicvectorizer.fit_transform(trainheadlines)
print(basictrain.shape)

(1741, 220649)

In [8]:
#Training a classifier - here Logistic

basicmodel = LogisticRegression(penalty = 'l1',C=0.2)
basicmodel = basicmodel.fit(basictrain, train["Direction"])

In [9]:
# Getting the test headlines 
# Predicting the direction of DJIA index

testheadlines = []
for row in range(0,len(test.index)):
    testheadlines.append(' '.join(str(x) for x in test.iloc[row,2:82]))
    
testheadlines[0]

" Inauguration Day in Albany  Governor Cuomo's Inaugural Address  The Early Word: a New Year, and New Issues  Pre-Inauguration Jitters for a High School Choir  What a Property Tax Cap Would Do  Missing Pieces Temper Knicks\xe2\x80\x99 Resurgence  Missing the A Train, and Taking Not-the-Quickest Way  Reminder for 2011: No Such Thing as Routine Chores  Career Shift Often Means Drop in Living Standards  Global Stock Markets Fight to Return From Recession  4th-Quarter Rally Lifts Hedge Fund To Robust Gains nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan"

In [10]:
basictest = basicvectorizer.transform(testheadlines)
predictions = basicmodel.predict(basictest)

In [11]:
print(predictions)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0
 1 0 0 1 0 0 0 0 0 0 1 0 0 1 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 1 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 1 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0
 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 1 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0]

In [12]:
pd.crosstab(test["Direction"], predictions, rownames=["Actual"], colnames=["Predicted"])

Predicted    0   1
Actual
0          416  29
1          229  31